# Generated by Django 5.0.3 on 2024-03-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usertarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
