# Generated by Django 5.0.3 on 2024-03-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fooditem_carbohydrates_fooditem_fat_fooditem_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(default=0),
        ),
    ]
